"""empty message

Revision ID: 4b40bfe6533f
Revises: 3390e723f62c
Create Date: 2024-02-09 15:51:33.455164

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '4b40bfe6533f'
down_revision = '3390e723f62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('dislike',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    if environment == "production":
        op.execute(f"ALTER TABLE likes SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('dislike',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
