"""empty message

Revision ID: 230d5998ad33
Revises: 73f53bbb8e0f
Create Date: 2024-03-05 09:24:33.657147

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '230d5998ad33'
down_revision = '73f53bbb8e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_column('dislike')
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('dislike', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
