"""empty message

Revision ID: ddcebb76441a
Revises: 08e1b7c0f35d
Create Date: 2024-02-12 18:50:26.527079

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'ddcebb76441a'
down_revision = '08e1b7c0f35d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('thread_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    if environment == "production":
        op.execute(f"ALTER TABLE images SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('thread_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
